sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script:
  - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libpython3.4m.so sbt ++$TRAVIS_SCALA_VERSION test


  # Trick to avoid unnecessary cache updates
  #- find $HOME/.sbt -name "*.lock" | xargs rm

scala:
  - 2.12.1

jdk:
  - oraclejdk8
  - openjdk8

notifications:
  email:
    - ganesh@thedatateam.in
