sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-pip
  - sudo apt-get install -y python3-numpy
  - sudo apt-get install -y python3-pandas

script:
  - sudo LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libpython3.4m.so LD_LIBRARY_PATH="/usr/lib:/usr/local/lib/python3.4/dist-packages/:/usr/local/lib/python3.4/dist-packages/jep"  sbt ++$TRAVIS_SCALA_VERSION test

  # Trick to avoid unnecessary cache updates
  #- find $HOME/.sbt -name "*.lock" | xargs rm

scala:
  - 2.12.1

jdk:
  - oraclejdk8
  - openjdk8

notifications:
  email:
    - ganesh@thedatateam.in
